/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "wrapper.go"

#include <stdint.h>
#include <stdlib.h>

typedef struct {
    char* data;
    int length;
} ByteArray;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int BTCDVerifyScript(ByteArray scriptSig, ByteArray scriptPubKey);
extern char* BTCDParseP2PMessage(ByteArray messageData);
extern char* BTCDAddrv2(ByteArray addrv2Data);
extern char* BTCDScriptAsm(ByteArray scriptData);
extern char* BTCDDesBlock(ByteArray scriptData);
extern void BTCDFreeString(char* ptr);

// BTCDMerkleRootCompute computes the merkle root over a list of raw 32-byte
// hashes (internal byte order, concatenated) and reports whether a duplicated
// subtree (CVE-2012-2459) was detected.
//
// btcd's exported merkle entry points (CalcMerkleRoot, BuildMerkleTreeStore)
// operate on []*btcutil.Tx rather than raw hashes, so the tree reduction
// below mirrors Bitcoin Core's ComputeMerkleRoot (duplicate the last hash on
// odd levels, hash pairs left to right) while the consensus-critical pair
// hashing itself is btcd's exported HashMerkleBranches (double SHA256 of the
// concatenated branches).
//
// Input: data is n*32 bytes (n >= 1; the driver never feeds empty lists).
// Output: "<root_hex>;mutated=0|1" with the root in display byte order.
//
extern char* BTCDMerkleRootCompute(ByteArray data);
// BTCDSighashCompute computes the legacy (SigVersion::BASE) or segwit v0
// (BIP143) signature hash for an input, emulating btcd's interpreter:
// truncate the script after the n-th executed OP_CODESEPARATOR and, for
// legacy, remove the pushed signature being checked.
//
// Input: txData is a serialized transaction; script the scriptCode with
// code separators intact; sigData the signature blob to delete (legacy only).
// Output: digest in display byte order, or nil when the input class is
// unsupported (tx parse failure, no inputs, or btcd's exported sighash API
// rejecting an unparseable script — the driver compares other modules then).
//
extern char* BTCDSighashCompute(ByteArray txData, ByteArray scriptData, ByteArray sigData, uint32_t inputIndex, uint32_t nCodesep, uint64_t amount, uint32_t sighashType, int isV0);
extern char* BTCDTransactionEval(ByteArray data);
extern char* BTCDParsePSBT(ByteArray data);
extern char* BTCDAddress(ByteArray data);
extern char* BTCDBip32MasterKeygen(ByteArray data);
extern char* BTCDSignSchnorr(ByteArray privKey, ByteArray hash, ByteArray aux);
extern char* BTCDDecodeEllswift(ByteArray buffer);
extern char* BTCDRoundtripEllswift(ByteArray buffer);
extern char* BTCDSchnorrVerify(ByteArray buffer, ByteArray hash, ByteArray sig);
extern char* BTCDBip32DeserializeExtendedKey(ByteArray data);

#ifdef __cplusplus
}
#endif
