/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "wrapper.go"

#include <stdint.h>
#include <stdlib.h>

typedef struct {
    char* data;
    int length;
} ByteArray;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int GocoinVerifyTxScript(ByteArray scriptSig, ByteArray scriptPubKey);

// GocoinEvalScript evaluates a Bitcoin script using gocoin's script engine.
// This is exported to C/C++ and will be called by the fuzzer.
//
// Parameters:
//   - scriptData: The raw script bytes to evaluate
//   - flags: Script verification flags (like VER_P2SH, VER_WITNESS, etc.)
//   - version: Signature version (0 = base, 1 = witness v0)
//
// Returns:
//   - 1 if script evaluation succeeded
//   - 0 if script is empty
//   - 2 if script evaluation failed
//
extern int GocoinEvalScript(ByteArray scriptData, uint32_t flags, size_t version);

// GocoinMerkleRootCompute computes the merkle root over a list of raw 32-byte
// hashes (internal byte order, concatenated) and reports whether a duplicated
// subtree (CVE-2012-2459) was detected.
//
// Input: data is n*32 bytes (n >= 1; the driver never feeds empty lists).
// Output: "<root_hex>;mutated=0|1" with the root in display byte order.
//
extern char* GocoinMerkleRootCompute(ByteArray data);
// GocoinSighashCompute computes the legacy (SIGVERSION_BASE) or segwit v0
// (BIP143) signature hash for an input, emulating gocoin's interpreter:
// truncate the script after the n-th executed OP_CODESEPARATOR and, for
// legacy, remove the pushed signature being checked.
//
// Output: digest in display byte order, or nil when the input class is
// unsupported (tx parse failure or no inputs).
//
extern char* GocoinSighashCompute(ByteArray txData, ByteArray scriptData, ByteArray sigData, uint32_t inputIndex, uint32_t nCodesep, uint64_t amount, uint32_t sighashType, int isV0);

// GocoinFreeString frees a C string that was allocated by Go.
// Must be called to prevent memory leaks.
//
extern void GocoinFreeString(char* ptr);

#ifdef __cplusplus
}
#endif
