// Single source of truth: (PREPROCESSOR_FLAG, "RegistryName", ClassName)

#ifdef BITCOIN_CORE
MODULE_ENTRY(BITCOIN_CORE, "BITCOIN_CORE", Bitcoin)
#endif
#ifdef RUST_BITCOIN
MODULE_ENTRY(RUST_BITCOIN, "RUST_BITCOIN", Rustbitcoin)
#endif
#ifdef RUST_PSBT
MODULE_ENTRY(RUST_PSBT, "RUST_PSBT", RustPsbt)
#endif
#ifdef RUST_MINISCRIPT
MODULE_ENTRY(RUST_MINISCRIPT, "RUST_MINISCRIPT", Rustminiscript)
#endif
#ifdef TINY_MINISCRIPT
MODULE_ENTRY(TINY_MINISCRIPT, "TINY_MINISCRIPT", Tinyminiscript)
#endif
#ifdef BITCOINERLAB_MINISCRIPT
MODULE_ENTRY(BITCOINERLAB_MINISCRIPT, "BITCOINERLAB_MINISCRIPT",
             BitcoinerlabMiniscript)
#endif
#ifdef BTCD
CGO_MODULE_ENTRY(BTCD, "BTCD", Btcd)
#endif
#ifdef GOCOIN
CGO_MODULE_ENTRY(GOCOIN, "GOCOIN", Gocoin)
#endif
#ifdef NBITCOIN
MODULE_ENTRY(NBITCOIN, "NBITCOIN", NBitcoin)
#endif
#ifdef LND
CGO_MODULE_ENTRY(LND, "LND", Lnd)
#endif
#ifdef LDK
MODULE_ENTRY(LDK, "LDK", Ldk)
#endif
#ifdef ECLAIR
MODULE_ENTRY(ECLAIR, "ECLAIR", Eclair)
#endif
#ifdef NLIGHTNING
MODULE_ENTRY(NLIGHTNING, "NLIGHTNING", NLightning)
#endif
#ifdef PYBITCOINKERNEL
MODULE_ENTRY(PYBITCOINKERNEL, "PYBITCOINKERNEL", Pybitcoinkernel)
#endif
#ifdef BITCOINKERNEL
MODULE_ENTRY(BITCOINKERNEL, "BITCOINKERNEL", BitcoinKernel)
#endif
#ifdef BITCOINKERNEL_VARIANT
MODULE_ENTRY(BITCOINKERNEL_VARIANT, "BITCOINKERNEL_VARIANT",
             BitcoinKernelVariant)
#endif
#ifdef RUSTBITCOINKERNEL
MODULE_ENTRY(RUSTBITCOINKERNEL, "RUSTBITCOINKERNEL", Rustbitcoinkernel)
#endif
#ifdef EMBIT
MODULE_ENTRY(EMBIT, "EMBIT", Embit)
#endif
#ifdef CLIGHTNING
MODULE_ENTRY(CLIGHTNING, "CLIGHTNING", CLightning)
#endif
#ifdef LIGHTNING_KMP
MODULE_ENTRY(LIGHTNING_KMP, "LIGHTNING_KMP", LightningKmp)
#endif
#ifdef BITCOINJ
MODULE_ENTRY(BITCOINJ, "BITCOINJ", BitcoinJ)
#endif
#ifdef BITCOINS
MODULE_ENTRY(BITCOINS, "BITCOINS", BitcoinS)
#endif
#ifdef DECRED_SECP256K1
CGO_MODULE_ENTRY(DECRED_SECP256K1, "DECRED_SECP256K1", Decred_secp256k1)
#endif
#ifdef SECP256K1
MODULE_ENTRY(SECP256K1, "SECP256K1", Secp256k1)
#endif
#ifdef NBITCOIN_SECP256K1
MODULE_ENTRY(NBITCOIN_SECP256K1, "NBITCOIN_SECP256K1", NBitcoin_secp256k1)
#endif
#ifdef RUST_K256
MODULE_ENTRY(RUST_K256, "RUST_K256", K256)
#endif
#ifdef LIBWALLY_CORE
MODULE_ENTRY(LIBWALLY_CORE, "LIBWALLY_CORE", LibwallyCore)
#endif
#ifdef RUSTREEXO
MODULE_ENTRY(RUSTREEXO, "RUSTREEXO", Rustreexo)
#endif
#ifdef UTREEXO
CGO_MODULE_ENTRY(UTREEXO, "UTREEXO", Utreexo)
#endif
#ifdef PYCOIN
MODULE_ENTRY(PYCOIN, "PYCOIN", Pycoin)
#endif
#ifdef LIBBITCOIN_SYSTEM
MODULE_ENTRY(LIBBITCOIN_SYSTEM, "LIBBITCOIN_SYSTEM", LibbitcoinSystem)
#endif
#ifdef RUST_MUSIG2
MODULE_ENTRY(RUST_MUSIG2, "RUST_MUSIG2", RustMusig2)
#endif
#ifdef RUSTCRYPTO_AES
MODULE_ENTRY(RUSTCRYPTO_AES, "RUSTCRYPTO_AES", RustCryptoAes)
#endif
#ifdef BOOST_MULTI_INDEX
MODULE_ENTRY(BOOST_MULTI_INDEX, "BOOST_MULTI_INDEX", BoostMultiIndex)
#endif
#ifdef TMI2
MODULE_ENTRY(TMI2, "TMI2", Tmi2)
#endif
#ifdef STD_CONTAINERS
MODULE_ENTRY(STD_CONTAINERS, "STD_CONTAINERS", StdContainers)
#endif
