name: Check

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout corpora repo
        uses: actions/checkout@v4
        with:
          repository: bitcoinfuzz/corpora
          path: corpora
          ref: main # Always get latest commit

      - name: Install rust-toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lowdown libsodium-dev libboost-all-dev npm nodejs quickjs libquickjs
          # libbitcoin-system requires CMake >= 3.30; Ubuntu 24.04 ships 3.28.3.
          # pip provides a binary cmake that takes precedence on PATH.
          python3 -m pip install --upgrade --break-system-packages 'cmake>=3.30'

      - name: Install Boost 1.86 (libbitcoin-system requires >= 1.86)
        uses: ./.github/actions/setup-boost-186

      - name: Setup common environment
        run: |
          export CC=/usr/bin/clang
          export CXX=/usr/bin/clang++
          echo "CC=/usr/bin/clang" >> $GITHUB_ENV
          echo "CXX=/usr/bin/clang++" >> $GITHUB_ENV

      - name: Save environment variables
        run: |
          echo "CC=$CC" >> build.env
          echo "CXX=$CXX" >> build.env

      - name: Setup Python and install embit and pybitcoinkernel and pycoin
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r modules/embit/requirements.txt
          pip install -r modules/pybitcoinkernel/requirements.txt
          pip install -r modules/pycoin/requirements.txt
          pip install -r modules/electrum/requirements.txt
          pip install mako

      - name: Build Modules
        timeout-minutes: 40
        run: |
          CXXFLAGS="-DBITCOIN_CORE \
          -DRUST_BITCOIN \
          -DRUSTBITCOINKERNEL \
          -DRUST_MINISCRIPT \
          -DBITCOINERLAB_MINISCRIPT \
          -DRUST_PSBT \
          -DRUST_MUSIG2 \
          -DRUSTCRYPTO_AES \
          -DBDK_SP \
          -DBLUEWALLET_SP \
          -DSPDK \
          -DBTCD \
          -DNBITCOIN \
          -DEMBIT \
          -DPYBITCOINKERNEL \
          -DBITCOINKERNEL \
          -DLND \
          -DLDK \
          -DNLIGHTNING \
          -DLIGHTNING_KMP \
          -DBITCOINJ \
          -DBITCOINS \
          -DCLIGHTNING \
          -DECLAIR \
          -DDECRED_SECP256K1 \
          -DSECP256K1 \
          -DNBITCOIN_SECP256K1 \
          -DRUST_K256 \
          -DGOCOIN \
          -DLIBWALLY_CORE \
          -DCUSTOM_MUTATOR_P2P_MESSAGE \
          -DRUSTREEXO \
          -DUTREEXO \
          -DPYCOIN \
          -DELECTRUM \
          -DLIBBITCOIN_SYSTEM" \
          ONLY_MODULES=1 \
          ./scripts/auto_build.py

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: bitcoinfuzz-build
          path: |
            modules/
            custommutator/
            bitcoinfuzz
            NBitcoin.CppBridge.so
            NBitcoin.CppBridge.dylib
            NBitcoinSecp256k1.CppBridge.so
            build.env
            external/secp256k1/include/
          if-no-files-found: error
          include-hidden-files: true
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        test:
          - corpus: "script"
            target: "script"
            cxxflags: "-DBITCOIN_CORE -DRUST_BITCOIN -DLIBBITCOIN_SYSTEM"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "deserialize_block"
            target: "deserialize_block"
            cxxflags: "-DBITCOIN_CORE -DRUST_BITCOIN -DBTCD -DLIBBITCOIN_SYSTEM"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "script_eval"
            target: "script_eval"
            cxxflags: "-DBITCOIN_CORE -DNBITCOIN -DLIBBITCOIN_SYSTEM"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "verify_script"
            target: "verify_script"
            cxxflags: "-DBITCOIN_CORE -DBTCD -DGOCOIN -DNBITCOIN -DLIBBITCOIN_SYSTEM"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "descriptor_parse_clean"
            target: "descriptor_parse"
            cxxflags: "-DBITCOIN_CORE -DRUST_MINISCRIPT"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "miniscript_parse_clean"
            target: "miniscript_parse"
            cxxflags: "-DBITCOIN_CORE -DRUST_MINISCRIPT -DBITCOINERLAB_MINISCRIPT"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "address_parse"
            target: "address_parse"
            cxxflags: "-DBITCOIN_CORE -DRUST_BITCOIN -DBTCD -DLIBBITCOIN_SYSTEM"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "psbt_parse_clean"
            target: "psbt_parse"
            cxxflags: "-DBITCOIN_CORE -DRUST_PSBT -DBTCD -DNBITCOIN -DLIBWALLY_CORE -DBITCOINS -DCUSTOM_MUTATOR_PSBT"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
            setup_java: "true"
          - corpus: "kernel_block"
            target: "kernel_block"
            cxxflags: "-DPYBITCOINKERNEL -DRUSTBITCOINKERNEL -DBITCOINKERNEL"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "kernel_transaction"
            target: "kernel_transaction"
            cxxflags: "-DPYBITCOINKERNEL -DRUSTBITCOINKERNEL -DBITCOINKERNEL"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "kernel_block_check"
            target: "kernel_block_check"
            cxxflags: "-DBITCOINKERNEL -DPYBITCOINKERNEL -DRUSTBITCOINKERNEL"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "cmpctblocks_parse"
            target: "cmpctblocks_parse"
            cxxflags: "-DBITCOIN_CORE -DRUST_BITCOIN"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "parse_p2p_message"
            target: "parse_p2p_message"
            cxxflags: "-DRUST_BITCOIN -DBTCD -DCUSTOM_MUTATOR_P2P_MESSAGE"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "deserialize_invoice_clean"
            target: "deserialize_invoice"
            cxxflags: "-DLDK -DLND -DCLIGHTNING -DECLAIR -DLIGHTNING_KMP -DCUSTOM_MUTATOR_BOLT11"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
            setup_java: "true"
          - corpus: "deserialize_offer_clean"
            target: "deserialize_offer"
            cxxflags: "-DLDK -DCLIGHTNING -DECLAIR -DLIGHTNING_KMP -DCUSTOM_MUTATOR_BOLT12_OFFER"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
            setup_java: "true"
          - corpus: "parse_p2p_lightning_message"
            target: "parse_p2p_lightning_message"
            cxxflags: "-DLDK -DCLIGHTNING -DLND -DCUSTOM_MUTATOR_P2P_LIGHTNING_MESSAGE"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "bip32_master_keygen"
            target: "bip32_master_keygen"
            cxxflags: "-DNBITCOIN -DRUST_BITCOIN -DBITCOIN_CORE -DBTCD -DBITCOINJ -DLIBWALLY_CORE -DELECTRUM -DEMBIT -DPYCOIN -DBITCOINS -DLIBBITCOIN_SYSTEM"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
            setup_java: "true"
          - corpus: "private_to_public_key"
            target: "private_to_public_key"
            cxxflags: "-DDECRED_SECP256K1 -DSECP256K1 -DNBITCOIN_SECP256K1 -DRUST_K256"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "pubkey_parse"
            target: "pubkey_parse"
            cxxflags: "-DSECP256K1 -DRUST_K256 -DDECRED_SECP256K1"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "sign_compact"
            target: "sign_compact"
            cxxflags: "-DDECRED_SECP256K1 -DSECP256K1 -DNBITCOIN_SECP256K1 -DRUST_K256"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "sign_der"
            target: "sign_der"
            cxxflags: "-DDECRED_SECP256K1 -DSECP256K1 -DNBITCOIN_SECP256K1 -DRUST_K256"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "merkle_root_compute"
            target: "merkle_root_compute"
            cxxflags: "-DBITCOIN_CORE -DRUST_BITCOIN -DBTCD -DGOCOIN"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "sign_verify"
            target: "sign_verify"
            cxxflags: "-DDECRED_SECP256K1 -DSECP256K1 -DNBITCOIN_SECP256K1 -DRUST_K256 -DCUSTOM_MUTATOR_SECP256K1_SIGNATURE"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "ecdh"
            target: "ecdh"
            cxxflags: "-DDECRED_SECP256K1 -DSECP256K1 -DNBITCOIN_SECP256K1 -DRUST_K256"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "sign_schnorr"
            target: "sign_schnorr"
            cxxflags: "-DBTCD -DSECP256K1 -DRUST_K256 -DNBITCOIN"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "bip32_deserialize_extended_key_clean"
            target: "bip32_deserialize_extended_key"
            cxxflags: "-DNBITCOIN -DRUST_BITCOIN -DBITCOIN_CORE -DBITCOINJ -DLIBWALLY_CORE -DELECTRUM -DEMBIT -DPYCOIN -DBITCOINS -DBTCD -DCUSTOM_MUTATOR_EXTENDED_KEY -DLIBBITCOIN_SYSTEM"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
            setup_java: "true"
          - corpus: "transaction_eval"
            target: "transaction_eval"
            cxxflags: "-DBITCOIN_CORE -DBITCOINKERNEL -DBTCD -DLIBBITCOIN_SYSTEM"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "decode_ellswift"
            target: "decode_ellswift"
            cxxflags: "-DBTCD -DSECP256K1 -DRUST_BITCOIN"
          - corpus: "roundtrip_ellswift"
            target: "roundtrip_ellswift"
            cxxflags: "-DBTCD -DSECP256K1 -DRUST_BITCOIN"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "schnorr_verify"
            target: "schnorr_verify"
            cxxflags: "-DBTCD -DSECP256K1 -DNBITCOIN_SECP256K1 -DCUSTOM_MUTATOR_SCHNORR_SIGNATURE"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "decode_onion"
            target: "decode_onion"
            cxxflags: "-DCLIGHTNING -DLND -DLDK -DCUSTOM_MUTATOR_ONION"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "stump_modify_add"
            target: "stump_modify_add"
            cxxflags: "-DRUSTREEXO -DUTREEXO"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "bip32_derive_from_path"
            target: "bip32_derive_from_path"
            cxxflags: "-DRUST_BITCOIN -DBITCOIN_CORE -DNBITCOIN"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "musig2_key_agg"
            target: "musig2_key_agg"
            cxxflags: "-DRUST_MUSIG2 -DSECP256K1"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "aes256_cbc"
            target: "aes256_cbc"
            cxxflags: "-DBITCOIN_CORE -DRUSTCRYPTO_AES"
          - corpus: "musig2_sign_session"
            target: "musig2_sign_session"
            cxxflags: "-DRUST_MUSIG2 -DSECP256K1"
            asan_options: "detect_leaks=0:detect_container_overflow=0"
          - corpus: "silentpayments_create_outputs"
            target: "silentpayments_create_outputs"
            cxxflags: "-DBDK_SP -DBLUEWALLET_SP -DSPDK -DSECP256K1"
            asan_options: "detect_leaks=0:detect_container_overflow=0"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-test-env

      - name: Load environment variables
        run: |
          if [ -f build.env ]; then
            cat build.env >> $GITHUB_ENV
          fi

      - name: Pre-build step
        if: matrix.test.pre_build != ''
        timeout-minutes: 5
        run: ${{ matrix.test.pre_build }}

      - name: Setup Java
        if: matrix.test.setup_java == 'true'
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Test - ${{ matrix.test.target }}
        timeout-minutes: 5
        run: |
          export CXX=/usr/bin/clang++
          FUZZ=${{ matrix.test.target }} ./.github/scripts/run-fuzz.sh \
          "${{ matrix.test.corpus }}" \
          "${{ matrix.test.target }}" \
          "${{ matrix.test.cxxflags }}" \
          "${{ matrix.test.asan_options }}" \
          "$CXX" \
          "-max_len=32768"
